```{r}
library(tidyverse)
library(ggpubr)
library(ggh4x)
```

```{r}
results <- tibble()

for (file in list.files('hamming_results')){
  data <- read_csv(paste0('hamming_results/',
                          file))
  
  name <- paste('MIPLIB:',
                sub("\\..*", "",
                    file))
  
  data <- data %>% 
    mutate(instance = rep(name, nrow(data)))
  
  results <- rbind(results, data)
}

results <- results %>% 
    mutate(weights = str_replace(weights, 'random', 'MORSE'),
           weights = str_replace(weights, 'uniform', 'Uniform Weights'),
           Method = str_replace(Method, 'Solution Pool', 'Arbitrary'))
```

```{r}
get_lim <- function(x){
  mult <- 100
  
  while (x * mult < 1){
    mult <- mult * 10
  }
  
  return(ceiling(x * mult)/mult)
}

order_by_max <- results %>%
  group_by(instance) %>%
  summarize(max_avg_hamming = max(avg_hamming)) %>%
  arrange(desc(max_avg_hamming)) %>% 
  mutate(max_avg_hamming = sapply(max_avg_hamming, get_lim)) %>% 
  ungroup() %>% 
  pull(instance)
```

```{r}
smoothed_lines <- results %>%
  group_by(Method, weights, instance) %>%
  do(model = loess(avg_hamming ~ sol_number, data = .)) %>% 
  ungroup()

points <- tibble()

results <- smoothed_lines %>% 
  rowwise() %>% 
  do({
    tibble(Method = rep(.$Method,
                        length(fitted(.$model))),
           weights = rep(.$weights,
                         length(fitted(.$model))),
           instance = rep(.$instance,
                          length(fitted(.$model))),
           sol_number = seq(1, length(fitted(.$model))),
           p = fitted(.$model)) %>% 
      left_join(results,
                by = c('Method',
                       'weights',
                       'instance',
                       'sol_number'))
  })

results$p <- ifelse(seq_along(results$p) %% 10 == 0,
                          results$p,
                          NA)
```

```{r}
results <- results %>% arrange(factor(instance, levels = order_by_max)) %>% 
  ungroup()
```

```{r}
options(scipen = 1)

results %>% 
  slice_head(n = nrow(results)/2) %>% 
  ggplot(aes(sol_number,
             avg_hamming,
             color = weights,
             shape = weights)) +
  geom_smooth() +
  geom_point(aes(y = p),
             size = 3,
             na.rm = TRUE) +
  scale_x_continuous(limits = c(0, 100),
                     breaks = c(25, 50, 75, 100),
                     labels = c(25, 50, 75, 100)) +
  scale_y_continuous(limits = c(0, NA)) +
  scale_color_brewer(palette = 'Set1') +
  theme_minimal() +
  labs(x = 'Run Number',
       y = 'Average Pairwise Hamming Distance Proportion',
       title = 'Average Pairwise Hamming Distance Proportion vs. Run Number',
       color = 'Optimization Method',
       shape = 'Optimization Method') +
  theme(plot.title = element_text(hjust = 0.5,
                                  size = 24),
        axis.title = element_text(size = 18),
        axis.text = element_text(size = 16),
        strip.background = element_rect(fill = 'grey90'),
        strip.text = element_text(face = 'bold',
                                  size = 14),
        legend.position = 'top',
        legend.direction = 'horizontal',
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 16),
        plot.margin = unit(c(0, 1, 0, 0),
                           'lines')) +
  facet_nested_wrap(. ~ factor(instance,
                               levels = order_by_max) +
                      factor(Method,
                             levels = c('Arbitrary',
                                        'Random Shuffle',
                                        'Greedy')),
                    ncol = 6,
                    scales = 'free_y') + scale_y_facet(PANEL == 1, limits = c(0,0.6), breaks = c(0, 0.3, 0.6)) + scale_y_facet(PANEL %in% c(2,3), limits = c(0, 0.6), labels = NULL, breaks = c(0, 0.3, 0.6)) + scale_y_facet(PANEL == 4, limits = c(0,0.6), breaks = c(0, 0.3, 0.6)) + scale_y_facet(PANEL %in% c(5,6), limits = c(0, 0.6), labels = NULL, breaks = c(0, 0.3, 0.6)) + scale_y_facet(PANEL == 7, limits = c(0,0.5), breaks = c(0, 0.25, 0.5)) + scale_y_facet(PANEL %in% c(8,9), limits = c(0, 0.5), labels = NULL, breaks = c(0, 0.25, 0.5)) + scale_y_facet(PANEL == 10, limits = c(0,0.4), breaks = c(0, 0.2, 0.4)) + scale_y_facet(PANEL %in% c(11,12), limits = c(0, 0.4), labels = NULL, breaks = c(0, 0.2, 0.4)) + scale_y_facet(PANEL == 13, limits = c(0,0.3), breaks = c(0, 0.15, 0.3)) + scale_y_facet(PANEL %in% c(14,15), limits = c(0, 0.3), labels = NULL, breaks = c(0, 0.15, 0.3)) + scale_y_facet(PANEL == 16, limits = c(0,0.2), breaks = c(0, 0.1, 0.2)) + scale_y_facet(PANEL %in% c(17,18), limits = c(0, 0.2), labels = NULL, breaks = c(0, 0.1, 0.2)) + scale_y_facet(PANEL == 19, limits = c(0.12,0.2), breaks = c(0.12, 0.16, 0.2)) + scale_y_facet(PANEL %in% c(20,21), limits = c(0.12, 0.2), labels = NULL, breaks = c(0.12, 0.16, 0.2)) + scale_y_facet(PANEL == 22, limits = c(0.12,0.18), breaks = c(0.12, 0.15, 0.18)) + scale_y_facet(PANEL %in% c(23,24), limits = c(0.12, 0.18), labels = NULL, breaks = c(0.12, 0.15, 0.18)) + scale_y_facet(PANEL == 25, limits = c(0,0.15)) + scale_y_facet(PANEL %in% c(26,27), limits = c(0, 0.15), labels = NULL) + scale_y_facet(PANEL == 28, limits = c(0.03,0.07), breaks = c(0.03, 0.05, 0.07)) + scale_y_facet(PANEL %in% c(29,30), limits = c(0.03, 0.07), labels = NULL, breaks = c(0.03, 0.05, 0.07))

ggsave('plots/hamming_split/hamming_group1.png', bg = 'white', width = 12, height = 12, units = 'in')
```

```{r}
options(scipen = 1)

results %>% 
  slice_tail(n = nrow(results)/2) %>% 
  ggplot(aes(sol_number,
             avg_hamming,
             color = weights,
             shape = weights)) +
  geom_smooth() +
  geom_point(aes(y = p),
             size = 3,
             na.rm = TRUE) +
  scale_x_continuous(limits = c(0, 100),
                     breaks = c(25, 50, 75, 100),
                     labels = c(25, 50, 75, 100)) +
  scale_y_continuous(limits = c(0, NA)) +
  scale_color_brewer(palette = 'Set1') +
  theme_minimal() +
  labs(x = 'Run Number',
       y = 'Average Pairwise Hamming Distance Proportion',
       title = 'Average Pairwise Hamming Distance Proportion vs. Run Number',
       color = 'Optimization Method',
       shape = 'Optimization Method') +
  theme(plot.title = element_text(hjust = 0.5,
                                  size = 24),
        axis.title = element_text(size = 18),
        axis.text = element_text(size = 16),
        strip.background = element_rect(fill = 'grey90'),
        strip.text = element_text(face = 'bold',
                                  size = 14),
        legend.position = 'top',
        legend.direction = 'horizontal',
        legend.text = element_text(size = 15),
        legend.title = element_text(size = 16),
        plot.margin = unit(c(0, 1, 0, 0),
                           'lines')) +
  facet_nested_wrap(. ~ factor(instance,
                               levels = order_by_max) +
                      factor(Method,
                             levels = c('Arbitrary',
                                        'Random Shuffle',
                                        'Greedy')),
                    ncol = 6,
                    scales = 'free_y') + scale_y_facet(PANEL == 1, limits = c(0,0.06), breaks = c(0, 0.03, 0.06)) + scale_y_facet(PANEL %in% c(2,3), limits = c(0, 0.06), labels = NULL, breaks = c(0, 0.03, 0.06)) + scale_y_facet(PANEL == 4, limits = c(0.03,0.07), breaks = c(0.03, 0.05, 0.07)) + scale_y_facet(PANEL %in% c(5,6), limits = c(0.03, 0.07), labels = NULL, breaks = c(0.03, 0.05, 0.07)) + scale_y_facet(PANEL == 7, limits = c(0.02,0.06), breaks = c(0.02, 0.04, 0.06)) + scale_y_facet(PANEL %in% c(8,9), limits = c(0.02, 0.06), labels = NULL, breaks = c(0.02, 0.04, 0.06)) + scale_y_facet(PANEL == 10, limits = c(0,0.04), breaks = c(0, 0.02, 0.04)) + scale_y_facet(PANEL %in% c(11,12), limits = c(0, 0.04), labels = NULL, breaks = c(0, 0.02, 0.04)) + scale_y_facet(PANEL == 13, limits = c(0,0.006), breaks = c(0, 0.003, 0.006)) + scale_y_facet(PANEL %in% c(14,15), limits = c(0, 0.006), labels = NULL, breaks = c(0, 0.003, 0.006)) + scale_y_facet(PANEL == 16, limits = c(0,0.006), breaks = c(0, 0.003, 0.006)) + scale_y_facet(PANEL %in% c(17,18), limits = c(0, 0.006), labels = NULL, breaks = c(0, 0.003, 0.006)) + scale_y_facet(PANEL == 19, limits = c(0,0.006), breaks = c(0, 0.003, 0.006)) + scale_y_facet(PANEL %in% c(20,21), limits = c(0, 0.006), labels = NULL, breaks = c(0, 0.003, 0.006)) + scale_y_facet(PANEL == 22, limits = c(0,0.007)) + scale_y_facet(PANEL %in% c(23,24), limits = c(0, 0.007), labels = NULL) + scale_y_facet(PANEL == 25, limits = c(0,0.004), breaks = c(0, 0.002, 0.004)) + scale_y_facet(PANEL %in% c(26,27), limits = c(0, 0.004), labels = NULL, breaks = c(0, 0.002, 0.004)) + scale_y_facet(PANEL == 28, limits = c(0.002,0.004), breaks = c(0.002, 0.003, 0.004)) + scale_y_facet(PANEL %in% c(29,30), limits = c(0.002, 0.004), labels = NULL, breaks = c(0.002, 0.003, 0.004))

ggsave('plots/hamming_split/hamming_group2.png', bg = 'white', width = 12, height = 12, units = 'in')
```