```{r}
library(tidyverse)
library(digest)
```

```{r}
entropy <- function(x){
  freq <- table(x)
  
  prob <- freq/sum(freq)
  
  -sum(prob * log2(prob))
                   
}

merged <- tibble()

for (instance in list.files('unique_results')){
  name <- paste('MIPLIB:',
                strsplit(instance, "_", fixed = TRUE)[[1]][1])
  
  if (grepl('uniform', instance)){
    weight = 'Uniform\nWeights'
  }
  else {
    weight = 'MORSE'
  }
  
  data <- read_csv(paste0('unique_results/',
                            instance), 
                     col_names = FALSE)
  
  merged <- rbind(merged,
                  tibble(shannon = entropy(data %>% apply(1, digest)),
                         avg_shannon = mean(apply(data, 2, entropy)),
                         Weights = weight,
                         instance = name))
  
}
```

```{r}
order_by_max <- merged %>%
  group_by(instance) %>%
  summarize(max_shannon = max(shannon)) %>%
  arrange(desc(max_shannon)) %>%
  pull(instance)
```


```{r}
merged %>%
  mutate(label = ifelse(shannon == 0,
                        NA,
                        round(shannon,
                              3)),
         vjust = ifelse(shannon < 0.1,
                        1.01,
                        1.4)) %>%
  ggplot(aes(Weights,
             shannon,
             fill = Weights,
             label = label)) +
  geom_bar(stat = 'identity',
           color = 'black') +
  geom_text(aes(vjust = vjust),
            position = 'dodge',
            fontface = 'bold',
            size = 8,
            na.rm = TRUE) +
  scale_fill_brewer(palette = 'Set1',
                    labels = c('MORSE',
                               'Uniform Weights')) +
  facet_wrap(~factor(instance, order_by_max),
             scales = 'free_y',
             ncol = 4) +
  theme_pubr() +
  labs(x = NULL,
       y = 'Shannon Entropy',
       title = 'Shannon Entropy vs. Optimization Method',
       fill = 'Optimization Method') +
  theme(plot.title = element_text(hjust = 0.5,
                                  size = 24),
        axis.title = element_text(size = 18),
        axis.text.y = element_text(size = 14),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        strip.background = element_rect(fill = 'grey90'),
        strip.text = element_text(face = 'bold',
                                  size = 14),
        legend.direction = 'horizontal',
        legend.position = 'top',
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 14))

ggsave('plots/shannon.png', width = 12, height = 16, units = 'in', bg = 'white')
```

```{r}
order_by_max_new <- merged %>%
  group_by(instance) %>%
  summarize(max_shannon = max(avg_shannon)) %>%
  arrange(desc(max_shannon)) %>%
  pull(instance)
```

```{r}
merged %>% 
  mutate(label = ifelse(avg_shannon == 0,
                        NA,
                        ifelse(avg_shannon < 0.001,
                               '<0.001',
                               round(avg_shannon,
                              3))),
         vjust = ifelse(avg_shannon < 0.001,
                        -0.2,
                        1.4)) %>%
  ggplot(aes(Weights,
             avg_shannon,
             fill = Weights,
             label = label)) +
  geom_bar(stat = 'identity',
           color = 'black') +
  geom_text(aes(vjust = vjust),
            position = 'dodge',
            fontface = 'bold',
            size = 8,
            na.rm = TRUE) +
  scale_fill_brewer(palette = 'Set1',
                    labels = c('MORSE',
                               'Uniform Weights')) +
  facet_wrap(~factor(instance, order_by_max_new),
             scales = 'free_y',
             ncol = 4) +
  theme_pubr() +
  labs(x = NULL,
       y = 'Average Shannon Entropy',
       title = 'Average Shannon Entropy vs. Optimization Method',
       fill = 'Optimization Method') +
  theme(plot.title = element_text(hjust = 0.5,
                                  size = 24),
        axis.title = element_text(size = 18),
        axis.text.x = element_blank(),
        axis.text.y = element_text(size = 14),
        axis.ticks.x = element_blank(),
        strip.background = element_rect(fill = 'grey90'),
        strip.text = element_text(face = 'bold',
                                  size = 14),
        legend.direction = 'horizontal',
        legend.position = 'top',
        legend.text = element_text(size = 14),
        legend.title = element_text(size = 14))

ggsave('plots/average_shannon.png', width = 12, height = 14, units = 'in', bg = 'white')
```