```{r}
library(tidyverse)
library(readxl)
```

```{r}
datasets <- c('GSE103322', 'GSE147082')

for (dataset in datasets){
  
  results <- read_excel(paste0('sols/',
                               dataset,
                               '.xlsx')) %>% 
    filter(lb == 0.8)
  
  
  cutoff <- if_else(dataset == 'GSE103322',
                    500,
                    1000)
  
  results_random <- results %>% 
    filter(type == 'random') %>%
    head(cutoff) %>% 
    mutate(run_number = rep(seq(1, cutoff)))
  
  results_uniform <- results %>% 
    filter(type == 'uniform') %>% 
    head(cutoff) %>% 
    mutate(run_number = rep(seq(1, cutoff)))
  
  random_num_sol <- sapply(results_random$run_number, function(x) length(unique(head(results_random$genes, x))))
  uniform_num_sol <- sapply(results_uniform$run_number, function(x) length(unique(head(results_uniform$genes, x))))
    
  run_counts <- rbind(tibble(num_sol = c(random_num_sol,
                                    uniform_num_sol),
                       Weights = c(rep('MORSE', cutoff),
                                    rep('Uniform Weights', cutoff)),
                       run_number = rep(seq(1, cutoff), 2)),
                      tibble(num_sol = c(0, 0),
                             run_number = c(0, 0),
                             Weights = c('MORSE', 'Uniform Weights'))) %>% 
    mutate(dataset = rep(paste('Dataset:',
                               dataset),
                         2 * cutoff + 2))
  
  
  run_counts$p <- ifelse(seq_along(run_counts$run_number) %% 50 == 0,
                         run_counts$num_sol,
                         NA)
  
  max_vals <- run_counts %>%
    group_by(dataset) %>%
    summarize(max_val = 1.1 * max(num_sol),
              max_run = max(run_number))
  
  run_counts %>% 
    ggplot(aes(run_number,
               num_sol)) +
    geom_line(aes(color = Weights),
              linewidth = 1) +
    geom_point(aes(y = p,
                   color = Weights,
                   shape = Weights),
               size = 4,
               na.rm = TRUE) +
    geom_blank(data = max_vals,
               aes(max_run,
                   max_val)) +
    scale_x_continuous(expand = c(0.01, 0.01),
                       limits = c(0, NA)) +
    scale_y_continuous(expand = c(0, 0),
                       limits = c(0, NA)) +
    scale_color_brewer(palette = 'Set1') +
    ggpubr::theme_pubr() +
    theme(legend.direction = 'horizontal',
          legend.position = 'top',
          plot.title = element_text(hjust = 0.5),
          plot.subtitle = element_text(hjust = 0.5,
                                       face = 'bold'),
          plot.margin = unit(c(1, 1, 1, 1),
                             'lines'),
          axis.text = element_text(size = 12),
          strip.background = element_rect(fill = 'grey90'),
          strip.text = element_text(face = 'bold',
                                    size = 12)) +
    labs(x = 'Run Number',
         y = 'Number of Distinct Optima Found',
         title = 'Number of Distinct Optima vs. Run Number',
         color = 'Optimization Method',
         shape = 'Optimization Method') +
    facet_grid(~dataset)
  
  ggsave(paste0('plots/',
               dataset,
               '.png'),
         bg = 'white',
         width = 7.29,
         height = 4.5,
         units = 'in')
  
}
```